name: 'Auto Retry Job'
description: 'Automatically retry failed jobs using GitHub run rerun'
author: 'drape-io'

inputs:
  max-attempts:
    description: 'Maximum retry attempts'
    required: false
    default: '3'
  retry-workflow:
    description: 'Workflow file to use for retries'
    required: false
    default: 'retry.yml'
  step-id:
    description: 'ID of step to check (required if using continue-on-error)'
    required: false

runs:
  using: composite
  steps:
    - name: Check for retry conditions
      if: always()
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # Determine if we should retry based on job status or step outcome
        SHOULD_RETRY="false"
        
        if [ -n "${{ inputs.step-id }}" ]; then
          # Check specific step outcome (for continue-on-error usage)
          if [ "${{ steps[inputs.step-id].outcome }}" = "failure" ] && [ ${{ github.run_attempt }} -lt ${{ inputs.max-attempts }} ]; then
            SHOULD_RETRY="true"
          fi
        else
          # Check job status (for standard failure usage)
          if [ "${{ job.status }}" = "failure" ] && [ ${{ github.run_attempt }} -lt ${{ inputs.max-attempts }} ]; then
            SHOULD_RETRY="true"
          fi
        fi
        
        if [ "$SHOULD_RETRY" = "true" ]; then
          echo "🔄 Job failed, triggering retry (attempt ${{ github.run_attempt }}/${{ inputs.max-attempts }})"
          echo "📊 Run ID: ${{ github.run_id }}"
          
          # Trigger retry workflow
          gh workflow run ${{ inputs.retry-workflow }} -f run_id="${{ github.run_id }}"
          
          echo "✅ Retry triggered successfully"
          echo "🔗 Monitor retries at: https://github.com/${{ github.repository }}/actions/workflows/${{ inputs.retry-workflow }}"
          
          # If using continue-on-error, we need to fail the job for proper status
          if [ -n "${{ inputs.step-id }}" ]; then
            echo "💥 Failing job to show correct status (continue-on-error was used)"
            exit 1
          fi
        else
          if [ -n "${{ inputs.step-id }}" ]; then
            echo "ℹ️ No retry needed (step succeeded or max attempts reached)"
          else
            echo "ℹ️ No retry needed (job succeeded or max attempts reached)"
          fi
        fi
